statsApiLink=https://www.pathofexile.com/api/trade/data/stats
statsApiLinkPoE2=https://www.pathofexile.com/api/trade2/data/stats
itemsApiLink=https://www.pathofexile.com/api/trade/data/items
itemsApiLinkPoE2=https://www.pathofexile.com/api/trade2/data/items
tradeApiSearchUrl=https://www.pathofexile.com/api/trade/search/
tradeApiSearchUrlPoE2=https://www.pathofexile.com/api/trade2/search/
tradeWebSearchUrl=https://www.pathofexile.com/trade/search/
tradeWebSearchUrlPoE2=https://www.pathofexile.com/trade2/search/poe2/
tradeApiRequestDelayMs=4000
